# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OOPS
version:      0.2003
version_from: lib/OOPS.pm
installdirs:  site
requires:
    DBI:                           1.4
    Digest::MD5:                   0
    Filter::Util::Call:            0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
